version: '3.9'

services:
  sqldb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql_catavento_db
    environment:
      SA_PASSWORD: "1q2w3e4r@#$"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql

volumes:
  sqldata: