version: '3.9'

services:
  postgresdb:
    image: postgres:14-alpine
    container_name: postgres_catavento_db
    environment:
      POSTGRES_USER: admin_catavento_db
      POSTGRES_PASSWORD: "1q2w3e4r@#$"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: